### ISSUE TITLE
crash in Writer.Close()

### ISSUE THREAD

**Issue by kjk** [kurin/blazer#17]
This is on Mac, go 1.8.3, blazer 022f731ca289fb294dc177d471e9e8ee4b78239f

This happened after uploading few thousands of files, so it's rare. There's no multi-threading (i.e. all uploads happen from the same thread).

crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x124764f]

goroutine 1 [running]:
github.com/kurin/blazer/b2.(*Writer).Close.func1()
	/Users/kjk/src/go/src/github.com/kurin/blazer/b2/writer.go:366 +0x6f
sync.(*Once).Do(0xc420a60098, 0xc42428b9f8)
	/usr/local/Cellar/go/1.8.3/libexec/src/sync/once.go:44 +0xbe
github.com/kurin/blazer/b2.(*Writer).Close(0xc420a60000, 0xc420a60000, 0x1422480)
	/Users/kjk/src/go/src/github.com/kurin/blazer/b2/writer.go:385 +0x58
main.BackblazeUploadFileWithMetadata(0xc421020dc0, 0x38, 0xc420ed1780, 0x75, 0xc42428bc68, 0x2, 0x2, 0x0, 0x0)
	/Users/kjk/src/kjkpriv/src/b2backup/backblaze.go:76 +0x3d0
main.backupFile2(0xc420ed1780, 0x75, 0x0, 0x1, 0x1)
	/Users/kjk/src/kjkpriv/src/b2backup/main.go:166 +0x3f7
main.backupDir(0x7fff5fbffa04, 0xf, 0xc420077180, 0x1, 0x1, 0xc420077190, 0x4)
	/Users/kjk/src/kjkpriv/src/b2backup/main.go:130 +0x2b4
main.main()
	/Users/kjk/src/kjkpriv/src/b2backup/main.go:315 +0x2f1
 ```

For your convenience, those are snippets of code that crash. `<-- crash` marks the line that crashes.

```go
func BackblazeUploadFileWithMetadata(b2path, path string, metadata []string) error {
	if len(metadata)%2 != 0 {
		return errInvalidMetadata
	}
	nMetadata := len(metadata) / 2
	if nMetadata > 10 {
		return errInvalidMetadata
	}
	src, err := os.Open(path)
	if err != nil {
		return err
	}
	defer src.Close()

	ctx := context.Background()
	bucket, err := getBucket(ctx)
	if err != nil {
		return err
	}

	obj := bucket.Object(b2path)

	dst := obj.NewWriter(ctx)

	if nMetadata > 0 {
		info := make(map[string]string)
		for i := 0; i < nMetadata; i++ {
			key, val := metadata[i*2], metadata[i*2+1]
			info[key] = val
		}

		// TODO: set attrs.ContentType ?
		attrs := b2.Attrs{
			Info: info,
		}
		dst = dst.WithAttrs(&attrs)
	}

	_, err = io.Copy(dst, src)
	err2 := dst.Close() <--- crash
	if err == nil {
		err = err2
	}
	return err
}
```

b2/writer.go

```go
func (w *Writer) Close() error {
	w.done.Do(func() {
		defer w.o.b.c.removeWriter(w)
		defer w.w.Close() // TODO: log error
		if w.cidx == 0 {
			w.setErr(w.simpleWriteFile())
			return
		}
		if w.w.Len() > 0 {
			if err := w.sendChunk(); err != nil {
				w.setErr(err)
				return
			}
		}
		close(w.ready)
		w.wg.Wait()
		f, err := w.file.finishLargeFile(w.ctx)
		if err != nil {
			w.setErr(err)
			return
		}
		w.o.f = f
	}) <-- crash
	return w.getErr()
}
```

sync/once.go:

```go
func (o *Once) Do(f func()) {
	if atomic.LoadUint32(&o.done) == 1 {
		return
	}
	// Slow-path.
	o.m.Lock()
	defer o.m.Unlock()
	if o.done == 0 {
		defer atomic.StoreUint32(&o.done, 1) <-- crash
		f()
	}
}
```

So it looks `o.done` was nil.

**Comment by kurin** [comment]
I'm pretty sure I've seen this and have a fix, I just don't have a test.

**Comment by kurin** [comment]
Was the file it was syncing zero bytes?

**Comment by kurin** [comment]
Try the most recent commit, 3758916, and see if that helps.

**Comment by kjk** [comment]
Yes, it was 0-byte sized file. I could repro the crash reliably and after update the crash is gone.

Thanks!
